"""Exercise database seeder — populates 50+ exercises on first run."""

from app.db.connection import get_database
from app.db.repositories.exercise_repo import ExerciseRepository


EXERCISES = [
    # === CHEST ===
    {
        "name": "Push-up",
        "description": "A classic bodyweight exercise that targets the chest, shoulders, and triceps.",
        "target_muscle": "chest",
        "secondary_muscles": ["triceps", "shoulders", "core"],
        "difficulty": "beginner",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 10,
        "default_duration_sec": None,
        "rest_time_sec": 60,
        "instructions": [
            "Start in a high plank position with hands shoulder-width apart",
            "Lower your body until your chest nearly touches the floor",
            "Keep your core tight and body in a straight line",
            "Push back up to the starting position",
        ],
        "common_mistakes": [
            "Flaring elbows too wide",
            "Sagging hips",
            "Not going low enough",
        ],
        "video_url": "https://www.youtube.com/watch?v=IODxDxX7oi4",
        "thumbnail_url": None,
        "calories_per_minute": 7.0,
    },
    {
        "name": "Incline Push-up",
        "description": "An easier push-up variation using an elevated surface.",
        "target_muscle": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "difficulty": "beginner",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 12,
        "default_duration_sec": None,
        "rest_time_sec": 60,
        "instructions": [
            "Place your hands on an elevated surface like a bench or step",
            "Keep your body straight from head to heels",
            "Lower your chest toward the surface",
            "Push back up to start",
        ],
        "common_mistakes": [
            "Surface too high or too low for your level",
            "Rounding the back",
        ],
        "video_url": "https://www.youtube.com/watch?v=Z4r2aIhSAh8",
        "thumbnail_url": None,
        "calories_per_minute": 5.0,
    },
    {
        "name": "Diamond Push-up",
        "description": "A challenging push-up variation emphasizing the triceps.",
        "target_muscle": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "difficulty": "advanced",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 8,
        "default_duration_sec": None,
        "rest_time_sec": 90,
        "instructions": [
            "Place hands close together forming a diamond shape under your chest",
            "Lower your body while keeping elbows close to your sides",
            "Push back up explosively",
        ],
        "common_mistakes": [
            "Hands too far forward",
            "Elbows flaring out",
        ],
        "video_url": "https://www.youtube.com/watch?v=J0DnG1_S3bg",
        "thumbnail_url": None,
        "calories_per_minute": 8.0,
    },
    {
        "name": "Wide Push-up",
        "description": "Push-up variation with wider hand placement for more chest activation.",
        "target_muscle": "chest",
        "secondary_muscles": ["shoulders", "triceps"],
        "difficulty": "intermediate",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 10,
        "default_duration_sec": None,
        "rest_time_sec": 60,
        "instructions": [
            "Place hands wider than shoulder-width apart",
            "Lower your chest toward the floor",
            "Push back up to starting position",
        ],
        "common_mistakes": [
            "Going too wide causing shoulder strain",
            "Not maintaining core tension",
        ],
        "video_url": "https://www.youtube.com/watch?v=eFOSh8v5RHY",
        "thumbnail_url": None,
        "calories_per_minute": 7.0,
    },
    {
        "name": "Dumbbell Bench Press",
        "description": "Classic chest exercise using dumbbells for a full range of motion.",
        "target_muscle": "chest",
        "secondary_muscles": ["triceps", "shoulders"],
        "difficulty": "intermediate",
        "equipment": "dumbbells",
        "category": "strength",
        "default_sets": 4,
        "default_reps": 10,
        "default_duration_sec": None,
        "rest_time_sec": 90,
        "instructions": [
            "Lie on a flat bench holding dumbbells above your chest",
            "Lower the dumbbells to chest level with controlled movement",
            "Press them back up until arms are fully extended",
        ],
        "common_mistakes": [
            "Bouncing the weights off your chest",
            "Uneven pressing",
        ],
        "video_url": "https://www.youtube.com/watch?v=VmB1G1K7v94",
        "thumbnail_url": None,
        "calories_per_minute": 6.0,
    },

    # === BACK ===
    {
        "name": "Superman Hold",
        "description": "A bodyweight exercise that strengthens the lower back and posterior chain.",
        "target_muscle": "back",
        "secondary_muscles": ["glutes", "hamstrings"],
        "difficulty": "beginner",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": None,
        "default_duration_sec": 20,
        "rest_time_sec": 45,
        "instructions": [
            "Lie face down with arms extended overhead",
            "Simultaneously lift your arms, chest, and legs off the floor",
            "Hold the position, squeezing your glutes and back",
            "Lower slowly back down",
        ],
        "common_mistakes": [
            "Jerking up too quickly",
            "Not engaging the glutes",
        ],
        "video_url": "https://www.youtube.com/watch?v=z6PJMT2y8GQ",
        "thumbnail_url": None,
        "calories_per_minute": 4.0,
    },
    {
        "name": "Pull-up",
        "description": "The king of back exercises, targeting lats and biceps.",
        "target_muscle": "back",
        "secondary_muscles": ["biceps", "shoulders"],
        "difficulty": "advanced",
        "equipment": "pull_up_bar",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 6,
        "default_duration_sec": None,
        "rest_time_sec": 120,
        "instructions": [
            "Hang from a bar with an overhand grip, hands shoulder-width apart",
            "Pull yourself up until your chin is above the bar",
            "Lower yourself with control",
        ],
        "common_mistakes": [
            "Using momentum or swinging",
            "Not going through full range of motion",
        ],
        "video_url": "https://www.youtube.com/watch?v=eGo4IYlbE5g",
        "thumbnail_url": None,
        "calories_per_minute": 8.0,
    },
    {
        "name": "Dumbbell Bent-Over Row",
        "description": "A compound back exercise that builds thickness and strength.",
        "target_muscle": "back",
        "secondary_muscles": ["biceps", "core"],
        "difficulty": "intermediate",
        "equipment": "dumbbells",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 10,
        "default_duration_sec": None,
        "rest_time_sec": 60,
        "instructions": [
            "Hinge at the hips with a dumbbell in each hand",
            "Keep your back flat and core engaged",
            "Pull the dumbbells toward your hips",
            "Lower with control",
        ],
        "common_mistakes": [
            "Rounding the back",
            "Using too much momentum",
        ],
        "video_url": "https://www.youtube.com/watch?v=roCP6wCXPqo",
        "thumbnail_url": None,
        "calories_per_minute": 6.0,
    },
    {
        "name": "Reverse Snow Angel",
        "description": "Great bodyweight exercise for upper back and rear deltoids.",
        "target_muscle": "back",
        "secondary_muscles": ["shoulders"],
        "difficulty": "beginner",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 10,
        "default_duration_sec": None,
        "rest_time_sec": 45,
        "instructions": [
            "Lie face down with arms at your sides, palms down",
            "Lift your chest and arms slightly off the floor",
            "Sweep your arms overhead in an arc, then back down",
        ],
        "common_mistakes": [
            "Lifting too high and straining the lower back",
            "Moving too fast",
        ],
        "video_url": "https://www.youtube.com/watch?v=Jfpd0LGP5Q0",
        "thumbnail_url": None,
        "calories_per_minute": 4.0,
    },

    # === SHOULDERS ===
    {
        "name": "Pike Push-up",
        "description": "A bodyweight shoulder press variation.",
        "target_muscle": "shoulders",
        "secondary_muscles": ["triceps", "chest"],
        "difficulty": "intermediate",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 8,
        "default_duration_sec": None,
        "rest_time_sec": 60,
        "instructions": [
            "Start in a downward dog position with hips high",
            "Bend your elbows to lower your head toward the floor",
            "Push back up to starting position",
        ],
        "common_mistakes": [
            "Not keeping hips high enough",
            "Flaring elbows too wide",
        ],
        "video_url": "https://www.youtube.com/watch?v=sposDXWEB0A",
        "thumbnail_url": None,
        "calories_per_minute": 7.0,
    },
    {
        "name": "Dumbbell Shoulder Press",
        "description": "Overhead pressing movement for shoulder development.",
        "target_muscle": "shoulders",
        "secondary_muscles": ["triceps"],
        "difficulty": "intermediate",
        "equipment": "dumbbells",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 10,
        "default_duration_sec": None,
        "rest_time_sec": 60,
        "instructions": [
            "Sit or stand holding dumbbells at shoulder level",
            "Press the weights overhead until arms are fully extended",
            "Lower back to shoulder level with control",
        ],
        "common_mistakes": [
            "Arching the back excessively",
            "Not using full range of motion",
        ],
        "video_url": "https://www.youtube.com/watch?v=qEwKCR5JCog",
        "thumbnail_url": None,
        "calories_per_minute": 6.0,
    },
    {
        "name": "Dumbbell Lateral Raise",
        "description": "Isolation exercise for the side deltoids.",
        "target_muscle": "shoulders",
        "secondary_muscles": [],
        "difficulty": "beginner",
        "equipment": "dumbbells",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 12,
        "default_duration_sec": None,
        "rest_time_sec": 45,
        "instructions": [
            "Stand with dumbbells at your sides",
            "Raise arms out to the sides until parallel with the floor",
            "Lower with control",
        ],
        "common_mistakes": [
            "Using too heavy weight",
            "Swinging the weights up",
        ],
        "video_url": "https://www.youtube.com/watch?v=3VcKaXpzqRo",
        "thumbnail_url": None,
        "calories_per_minute": 4.0,
    },
    {
        "name": "Arm Circles",
        "description": "Simple shoulder warm-up and endurance exercise.",
        "target_muscle": "shoulders",
        "secondary_muscles": [],
        "difficulty": "beginner",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": None,
        "default_duration_sec": 30,
        "rest_time_sec": 30,
        "instructions": [
            "Extend arms out to the sides at shoulder height",
            "Make small circles, gradually increasing size",
            "Reverse direction halfway through",
        ],
        "common_mistakes": [
            "Going too fast",
            "Dropping the arms below shoulder height",
        ],
        "video_url": "https://www.youtube.com/watch?v=UGEpQ1BRx-4",
        "thumbnail_url": None,
        "calories_per_minute": 3.0,
    },

    # === BICEPS ===
    {
        "name": "Dumbbell Bicep Curl",
        "description": "The classic arm exercise for bicep size and strength.",
        "target_muscle": "biceps",
        "secondary_muscles": ["forearms"],
        "difficulty": "beginner",
        "equipment": "dumbbells",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 12,
        "default_duration_sec": None,
        "rest_time_sec": 45,
        "instructions": [
            "Stand with dumbbells at your sides, palms facing forward",
            "Curl the weights up toward your shoulders",
            "Squeeze at the top, then lower with control",
        ],
        "common_mistakes": [
            "Swinging the body",
            "Not using full range of motion",
        ],
        "video_url": "https://www.youtube.com/watch?v=ykJmrZ5v0Oo",
        "thumbnail_url": None,
        "calories_per_minute": 4.0,
    },
    {
        "name": "Hammer Curl",
        "description": "Bicep curl variation that also targets the forearms.",
        "target_muscle": "biceps",
        "secondary_muscles": ["forearms"],
        "difficulty": "beginner",
        "equipment": "dumbbells",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 12,
        "default_duration_sec": None,
        "rest_time_sec": 45,
        "instructions": [
            "Hold dumbbells with palms facing each other",
            "Curl the weights up keeping palms facing in",
            "Lower slowly",
        ],
        "common_mistakes": [
            "Using momentum",
            "Lifting elbows",
        ],
        "video_url": "https://www.youtube.com/watch?v=zC3nLlEvin4",
        "thumbnail_url": None,
        "calories_per_minute": 4.0,
    },

    # === TRICEPS ===
    {
        "name": "Tricep Dip (Bench)",
        "description": "Bodyweight tricep exercise using a bench or chair.",
        "target_muscle": "triceps",
        "secondary_muscles": ["chest", "shoulders"],
        "difficulty": "beginner",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 10,
        "default_duration_sec": None,
        "rest_time_sec": 60,
        "instructions": [
            "Sit on the edge of a bench with hands gripping the edge",
            "Slide off the bench and lower your body by bending elbows",
            "Push back up to the starting position",
        ],
        "common_mistakes": [
            "Going too deep causing shoulder strain",
            "Flaring elbows out",
        ],
        "video_url": "https://www.youtube.com/watch?v=6kALZikXxLc",
        "thumbnail_url": None,
        "calories_per_minute": 6.0,
    },
    {
        "name": "Overhead Tricep Extension",
        "description": "Isolation exercise targeting the long head of the tricep.",
        "target_muscle": "triceps",
        "secondary_muscles": [],
        "difficulty": "intermediate",
        "equipment": "dumbbells",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 10,
        "default_duration_sec": None,
        "rest_time_sec": 60,
        "instructions": [
            "Hold a dumbbell overhead with both hands",
            "Lower it behind your head by bending at the elbows",
            "Extend arms back up to the starting position",
        ],
        "common_mistakes": [
            "Flaring elbows too wide",
            "Using too heavy weight",
        ],
        "video_url": "https://www.youtube.com/watch?v=YbX7Wd8jQ-Q",
        "thumbnail_url": None,
        "calories_per_minute": 4.0,
    },
    {
        "name": "Tricep Kickback",
        "description": "Isolation exercise for tricep definition.",
        "target_muscle": "triceps",
        "secondary_muscles": [],
        "difficulty": "beginner",
        "equipment": "dumbbells",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 12,
        "default_duration_sec": None,
        "rest_time_sec": 45,
        "instructions": [
            "Hinge forward at the hips holding dumbbells",
            "Keep upper arms parallel to the floor",
            "Extend forearms back, squeezing the triceps",
            "Return to start with control",
        ],
        "common_mistakes": [
            "Swinging the weight",
            "Dropping the elbow",
        ],
        "video_url": "https://www.youtube.com/watch?v=ZO81bExngMI",
        "thumbnail_url": None,
        "calories_per_minute": 4.0,
    },

    # === CORE ===
    {
        "name": "Plank",
        "description": "Isometric core exercise that builds stability and endurance.",
        "target_muscle": "core",
        "secondary_muscles": ["shoulders", "glutes"],
        "difficulty": "beginner",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": None,
        "default_duration_sec": 30,
        "rest_time_sec": 45,
        "instructions": [
            "Support your body on your forearms and toes",
            "Keep your body in a straight line from head to heels",
            "Engage your core and hold",
        ],
        "common_mistakes": [
            "Sagging hips",
            "Piking hips too high",
            "Holding breath",
        ],
        "video_url": "https://www.youtube.com/watch?v=ASdvN_XEl_c",
        "thumbnail_url": None,
        "calories_per_minute": 4.0,
    },
    {
        "name": "Bicycle Crunch",
        "description": "Dynamic core exercise targeting obliques and rectus abdominis.",
        "target_muscle": "core",
        "secondary_muscles": [],
        "difficulty": "intermediate",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 20,
        "default_duration_sec": None,
        "rest_time_sec": 45,
        "instructions": [
            "Lie on your back with hands behind your head",
            "Bring one knee toward your chest while rotating to bring the opposite elbow toward it",
            "Alternate sides in a pedaling motion",
        ],
        "common_mistakes": [
            "Pulling on the neck",
            "Going too fast without control",
        ],
        "video_url": "https://www.youtube.com/watch?v=9FGilxCbdz8",
        "thumbnail_url": None,
        "calories_per_minute": 6.0,
    },
    {
        "name": "Dead Bug",
        "description": "Anti-extension core exercise great for beginners.",
        "target_muscle": "core",
        "secondary_muscles": [],
        "difficulty": "beginner",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 10,
        "default_duration_sec": None,
        "rest_time_sec": 45,
        "instructions": [
            "Lie on your back with arms pointing to the ceiling and knees bent at 90 degrees",
            "Slowly extend one arm and the opposite leg",
            "Return to start and repeat on the other side",
        ],
        "common_mistakes": [
            "Arching the lower back",
            "Moving too quickly",
        ],
        "video_url": "https://www.youtube.com/watch?v=I5xbsA71v4g",
        "thumbnail_url": None,
        "calories_per_minute": 4.0,
    },
    {
        "name": "Mountain Climber",
        "description": "Dynamic core and cardio exercise.",
        "target_muscle": "core",
        "secondary_muscles": ["shoulders", "quadriceps", "cardio"],
        "difficulty": "intermediate",
        "equipment": "none",
        "category": "cardio",
        "default_sets": 3,
        "default_reps": None,
        "default_duration_sec": 30,
        "rest_time_sec": 45,
        "instructions": [
            "Start in a high plank position",
            "Drive one knee toward your chest",
            "Quickly switch legs in a running motion",
            "Keep your core tight and hips level",
        ],
        "common_mistakes": [
            "Bouncing hips up and down",
            "Not fully extending the back leg",
        ],
        "video_url": "https://www.youtube.com/watch?v=nmwgirgXLYM",
        "thumbnail_url": None,
        "calories_per_minute": 10.0,
    },
    {
        "name": "Russian Twist",
        "description": "Rotational core exercise for oblique strength.",
        "target_muscle": "core",
        "secondary_muscles": [],
        "difficulty": "intermediate",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 20,
        "default_duration_sec": None,
        "rest_time_sec": 45,
        "instructions": [
            "Sit with knees bent, lean back slightly",
            "Twist your torso to one side, then the other",
            "Keep your feet off the ground for added difficulty",
        ],
        "common_mistakes": [
            "Rounding the back",
            "Moving only the arms instead of rotating the torso",
        ],
        "video_url": "https://www.youtube.com/watch?v=wkD8rjkodUI",
        "thumbnail_url": None,
        "calories_per_minute": 5.0,
    },
    {
        "name": "Leg Raise",
        "description": "Lower ab exercise performed lying on the floor.",
        "target_muscle": "core",
        "secondary_muscles": [],
        "difficulty": "intermediate",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 12,
        "default_duration_sec": None,
        "rest_time_sec": 60,
        "instructions": [
            "Lie flat on your back with legs straight",
            "Raise your legs to 90 degrees while keeping them straight",
            "Lower them slowly without letting them touch the floor",
        ],
        "common_mistakes": [
            "Arching the lower back",
            "Using momentum",
        ],
        "video_url": "https://www.youtube.com/watch?v=JB2oyawG9KI",
        "thumbnail_url": None,
        "calories_per_minute": 5.0,
    },
    {
        "name": "Side Plank",
        "description": "Lateral core stability exercise targeting obliques.",
        "target_muscle": "core",
        "secondary_muscles": ["shoulders"],
        "difficulty": "intermediate",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": None,
        "default_duration_sec": 25,
        "rest_time_sec": 45,
        "instructions": [
            "Lie on your side with your elbow under your shoulder",
            "Lift your hips so your body forms a straight line",
            "Hold the position, then switch sides",
        ],
        "common_mistakes": [
            "Letting hips sag",
            "Not stacking shoulders properly",
        ],
        "video_url": "https://www.youtube.com/watch?v=K2VljzCC16g",
        "thumbnail_url": None,
        "calories_per_minute": 4.0,
    },

    # === QUADRICEPS / LEGS ===
    {
        "name": "Bodyweight Squat",
        "description": "Fundamental lower body exercise targeting quads and glutes.",
        "target_muscle": "quadriceps",
        "secondary_muscles": ["glutes", "hamstrings", "core"],
        "difficulty": "beginner",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 12,
        "default_duration_sec": None,
        "rest_time_sec": 60,
        "instructions": [
            "Stand with feet shoulder-width apart",
            "Lower your hips back and down as if sitting in a chair",
            "Keep your chest up and knees tracking over toes",
            "Stand back up by driving through your heels",
        ],
        "common_mistakes": [
            "Knees caving inward",
            "Rounding the back",
            "Not going deep enough",
        ],
        "video_url": "https://www.youtube.com/watch?v=aclHkVaku9U",
        "thumbnail_url": None,
        "calories_per_minute": 6.0,
    },
    {
        "name": "Lunge",
        "description": "Unilateral leg exercise for balance and strength.",
        "target_muscle": "quadriceps",
        "secondary_muscles": ["glutes", "hamstrings"],
        "difficulty": "beginner",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 10,
        "default_duration_sec": None,
        "rest_time_sec": 60,
        "instructions": [
            "Step forward with one leg",
            "Lower your hips until both knees are bent at 90 degrees",
            "Push back to the starting position",
            "Alternate legs",
        ],
        "common_mistakes": [
            "Front knee going past the toes",
            "Leaning too far forward",
        ],
        "video_url": "https://www.youtube.com/watch?v=QOVaHwm-Q6U",
        "thumbnail_url": None,
        "calories_per_minute": 6.0,
    },
    {
        "name": "Jump Squat",
        "description": "Explosive lower body exercise combining strength and cardio.",
        "target_muscle": "quadriceps",
        "secondary_muscles": ["glutes", "calves", "cardio"],
        "difficulty": "intermediate",
        "equipment": "none",
        "category": "cardio",
        "default_sets": 3,
        "default_reps": 10,
        "default_duration_sec": None,
        "rest_time_sec": 60,
        "instructions": [
            "Perform a regular squat",
            "Explode upward jumping as high as you can",
            "Land softly and immediately go into the next rep",
        ],
        "common_mistakes": [
            "Landing with stiff legs",
            "Not squatting deep enough before jumping",
        ],
        "video_url": "https://www.youtube.com/watch?v=A-cFYWvaHr0",
        "thumbnail_url": None,
        "calories_per_minute": 10.0,
    },
    {
        "name": "Wall Sit",
        "description": "Isometric leg exercise building quad endurance.",
        "target_muscle": "quadriceps",
        "secondary_muscles": ["glutes"],
        "difficulty": "beginner",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": None,
        "default_duration_sec": 30,
        "rest_time_sec": 60,
        "instructions": [
            "Lean against a wall with your feet shoulder-width apart",
            "Slide down until your thighs are parallel to the floor",
            "Hold the position",
        ],
        "common_mistakes": [
            "Knees going past toes",
            "Not going low enough",
        ],
        "video_url": "https://www.youtube.com/watch?v=y-wV4Venusw",
        "thumbnail_url": None,
        "calories_per_minute": 4.0,
    },
    {
        "name": "Bulgarian Split Squat",
        "description": "Advanced single-leg squat with rear foot elevated.",
        "target_muscle": "quadriceps",
        "secondary_muscles": ["glutes", "hamstrings"],
        "difficulty": "advanced",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 8,
        "default_duration_sec": None,
        "rest_time_sec": 90,
        "instructions": [
            "Stand a few feet in front of a bench",
            "Place one foot behind you on the bench",
            "Lower your hips until your front thigh is parallel to the floor",
            "Push back up through your front heel",
        ],
        "common_mistakes": [
            "Standing too close to the bench",
            "Leaning too far forward",
        ],
        "video_url": "https://www.youtube.com/watch?v=2C-uNgKwPLE",
        "thumbnail_url": None,
        "calories_per_minute": 7.0,
    },
    {
        "name": "Goblet Squat",
        "description": "Weighted squat holding a dumbbell at chest level.",
        "target_muscle": "quadriceps",
        "secondary_muscles": ["glutes", "core"],
        "difficulty": "intermediate",
        "equipment": "dumbbells",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 10,
        "default_duration_sec": None,
        "rest_time_sec": 60,
        "instructions": [
            "Hold a dumbbell vertically at chest height",
            "Squat down keeping your elbows inside your knees",
            "Drive through your heels to stand back up",
        ],
        "common_mistakes": [
            "Letting the dumbbell pull you forward",
            "Not going deep enough",
        ],
        "video_url": "https://www.youtube.com/watch?v=MeIiIdhvXT4",
        "thumbnail_url": None,
        "calories_per_minute": 7.0,
    },

    # === HAMSTRINGS ===
    {
        "name": "Glute Bridge",
        "description": "Floor exercise targeting glutes and hamstrings.",
        "target_muscle": "hamstrings",
        "secondary_muscles": ["glutes", "core"],
        "difficulty": "beginner",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 12,
        "default_duration_sec": None,
        "rest_time_sec": 45,
        "instructions": [
            "Lie on your back with knees bent and feet flat on the floor",
            "Drive through your heels to lift your hips",
            "Squeeze your glutes at the top",
            "Lower slowly back down",
        ],
        "common_mistakes": [
            "Hyperextending the lower back",
            "Pushing through toes instead of heels",
        ],
        "video_url": "https://www.youtube.com/watch?v=8bbE64NuDTU",
        "thumbnail_url": None,
        "calories_per_minute": 4.0,
    },
    {
        "name": "Single-Leg Deadlift",
        "description": "Unilateral hip-hinge exercise for balance and posterior chain strength.",
        "target_muscle": "hamstrings",
        "secondary_muscles": ["glutes", "core"],
        "difficulty": "intermediate",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 8,
        "default_duration_sec": None,
        "rest_time_sec": 60,
        "instructions": [
            "Stand on one leg with a slight knee bend",
            "Hinge at the hips, extending the free leg behind you",
            "Lower your torso until nearly parallel to the floor",
            "Return to standing",
        ],
        "common_mistakes": [
            "Rounding the back",
            "Rotating the hips",
        ],
        "video_url": "https://www.youtube.com/watch?v=iDKmW_5rin4",
        "thumbnail_url": None,
        "calories_per_minute": 5.0,
    },
    {
        "name": "Good Morning",
        "description": "Hip hinge exercise focusing on hamstrings and lower back.",
        "target_muscle": "hamstrings",
        "secondary_muscles": ["back", "glutes"],
        "difficulty": "intermediate",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 10,
        "default_duration_sec": None,
        "rest_time_sec": 60,
        "instructions": [
            "Stand with feet hip-width apart, hands behind your head",
            "Hinge at the hips pushing them back",
            "Lower your torso until you feel a stretch in your hamstrings",
            "Return to standing by squeezing glutes",
        ],
        "common_mistakes": [
            "Rounding the back",
            "Going too deep without flexibility",
        ],
        "video_url": "https://www.youtube.com/watch?v=YA-h3n9L4YU",
        "thumbnail_url": None,
        "calories_per_minute": 5.0,
    },

    # === GLUTES ===
    {
        "name": "Donkey Kick",
        "description": "Isolation exercise for the glutes performed on all fours.",
        "target_muscle": "glutes",
        "secondary_muscles": ["hamstrings", "core"],
        "difficulty": "beginner",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 12,
        "default_duration_sec": None,
        "rest_time_sec": 45,
        "instructions": [
            "Start on all fours with hands under shoulders and knees under hips",
            "Keeping knee bent, lift one leg toward the ceiling",
            "Squeeze your glute at the top",
            "Lower and repeat, then switch sides",
        ],
        "common_mistakes": [
            "Arching the lower back",
            "Swinging the leg instead of controlled movements",
        ],
        "video_url": "https://www.youtube.com/watch?v=iMIKMR0DBGM",
        "thumbnail_url": None,
        "calories_per_minute": 4.0,
    },
    {
        "name": "Fire Hydrant",
        "description": "Hip abduction exercise targeting outer glutes.",
        "target_muscle": "glutes",
        "secondary_muscles": ["core"],
        "difficulty": "beginner",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 12,
        "default_duration_sec": None,
        "rest_time_sec": 45,
        "instructions": [
            "Start on all fours",
            "Keeping knee bent, lift one leg out to the side",
            "Raise until thigh is parallel to the floor",
            "Lower and repeat, then switch sides",
        ],
        "common_mistakes": [
            "Shifting weight to the opposite side",
            "Rotating the torso",
        ],
        "video_url": "https://www.youtube.com/watch?v=La3xzjsSVsI",
        "thumbnail_url": None,
        "calories_per_minute": 4.0,
    },
    {
        "name": "Hip Thrust",
        "description": "The most effective glute-building exercise.",
        "target_muscle": "glutes",
        "secondary_muscles": ["hamstrings", "core"],
        "difficulty": "intermediate",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 12,
        "default_duration_sec": None,
        "rest_time_sec": 60,
        "instructions": [
            "Sit on the floor with upper back against a bench",
            "Roll a barbell or place weight on your hips (or use bodyweight)",
            "Drive through heels to lift hips until body forms a straight line",
            "Squeeze glutes at the top and lower with control",
        ],
        "common_mistakes": [
            "Hyperextending at the top",
            "Not driving through heels",
        ],
        "video_url": "https://www.youtube.com/watch?v=SEdqd1n0cvg",
        "thumbnail_url": None,
        "calories_per_minute": 5.0,
    },

    # === CALVES ===
    {
        "name": "Calf Raise",
        "description": "Simple exercise to build calf strength and definition.",
        "target_muscle": "calves",
        "secondary_muscles": [],
        "difficulty": "beginner",
        "equipment": "none",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 15,
        "default_duration_sec": None,
        "rest_time_sec": 30,
        "instructions": [
            "Stand with feet hip-width apart",
            "Rise up on your toes as high as possible",
            "Hold briefly at the top",
            "Lower slowly back down",
        ],
        "common_mistakes": [
            "Bouncing at the bottom",
            "Not going through full range of motion",
        ],
        "video_url": "https://www.youtube.com/watch?v=-M4-G8p8fmc",
        "thumbnail_url": None,
        "calories_per_minute": 3.0,
    },

    # === FULL BODY ===
    {
        "name": "Burpee",
        "description": "Full body explosive exercise combining squat, push-up, and jump.",
        "target_muscle": "full_body",
        "secondary_muscles": ["chest", "quadriceps", "core", "shoulders"],
        "difficulty": "intermediate",
        "equipment": "none",
        "category": "cardio",
        "default_sets": 3,
        "default_reps": 8,
        "default_duration_sec": None,
        "rest_time_sec": 90,
        "instructions": [
            "Stand with feet shoulder-width apart",
            "Drop into a squat and place hands on the floor",
            "Jump feet back into a plank and do a push-up",
            "Jump feet forward and explode up into a jump",
        ],
        "common_mistakes": [
            "Skipping the push-up",
            "Not fully extending during the jump",
        ],
        "video_url": "https://www.youtube.com/watch?v=TU8QYVW0gDU",
        "thumbnail_url": None,
        "calories_per_minute": 12.0,
    },
    {
        "name": "Bear Crawl",
        "description": "Full body crawling movement for coordination and core strength.",
        "target_muscle": "full_body",
        "secondary_muscles": ["shoulders", "core", "quadriceps"],
        "difficulty": "intermediate",
        "equipment": "none",
        "category": "cardio",
        "default_sets": 3,
        "default_reps": None,
        "default_duration_sec": 30,
        "rest_time_sec": 60,
        "instructions": [
            "Start on all fours with knees hovering just above the ground",
            "Move forward by stepping opposite hand and foot together",
            "Keep your hips level and core engaged",
        ],
        "common_mistakes": [
            "Raising hips too high",
            "Moving same-side hand and foot together",
        ],
        "video_url": "https://www.youtube.com/watch?v=kOwCa-k_fR4",
        "thumbnail_url": None,
        "calories_per_minute": 9.0,
    },
    {
        "name": "Inchworm",
        "description": "Full body warm-up exercise combining a walk-out and walk-in.",
        "target_muscle": "full_body",
        "secondary_muscles": ["hamstrings", "core", "shoulders"],
        "difficulty": "beginner",
        "equipment": "none",
        "category": "flexibility",
        "default_sets": 3,
        "default_reps": 6,
        "default_duration_sec": None,
        "rest_time_sec": 45,
        "instructions": [
            "Stand tall, then bend at the hips and place hands on the floor",
            "Walk your hands out to a plank position",
            "Walk your hands back toward your feet",
            "Stand up and repeat",
        ],
        "common_mistakes": [
            "Bending the knees too much",
            "Rushing through the movement",
        ],
        "video_url": "https://www.youtube.com/watch?v=VSp0z0QPoj0",
        "thumbnail_url": None,
        "calories_per_minute": 5.0,
    },

    # === CARDIO ===
    {
        "name": "Jumping Jack",
        "description": "Classic cardio exercise for warm-up and calorie burn.",
        "target_muscle": "cardio",
        "secondary_muscles": ["full_body"],
        "difficulty": "beginner",
        "equipment": "none",
        "category": "cardio",
        "default_sets": 3,
        "default_reps": None,
        "default_duration_sec": 30,
        "rest_time_sec": 30,
        "instructions": [
            "Stand with feet together and arms at your sides",
            "Jump feet apart while raising arms overhead",
            "Jump back to starting position",
            "Repeat at a steady pace",
        ],
        "common_mistakes": [
            "Landing with stiff legs",
            "Not fully extending arms overhead",
        ],
        "video_url": "https://www.youtube.com/watch?v=c4DAnQ6DtF8",
        "thumbnail_url": None,
        "calories_per_minute": 8.0,
    },
    {
        "name": "High Knees",
        "description": "Cardio exercise that elevates heart rate and works the core.",
        "target_muscle": "cardio",
        "secondary_muscles": ["core", "quadriceps"],
        "difficulty": "beginner",
        "equipment": "none",
        "category": "cardio",
        "default_sets": 3,
        "default_reps": None,
        "default_duration_sec": 30,
        "rest_time_sec": 30,
        "instructions": [
            "Stand with feet hip-width apart",
            "Drive one knee up toward your chest",
            "Quickly alternate legs in a running motion",
            "Pump your arms for momentum",
        ],
        "common_mistakes": [
            "Leaning too far back",
            "Not bringing knees high enough",
        ],
        "video_url": "https://www.youtube.com/watch?v=D0FPqxPnbSI",
        "thumbnail_url": None,
        "calories_per_minute": 9.0,
    },
    {
        "name": "Butt Kick",
        "description": "Cardio drill that targets hamstrings while elevating heart rate.",
        "target_muscle": "cardio",
        "secondary_muscles": ["hamstrings"],
        "difficulty": "beginner",
        "equipment": "none",
        "category": "cardio",
        "default_sets": 3,
        "default_reps": None,
        "default_duration_sec": 30,
        "rest_time_sec": 30,
        "instructions": [
            "Stand with feet hip-width apart",
            "Jog in place, kicking your heels up toward your glutes",
            "Keep your core engaged and arms pumping",
        ],
        "common_mistakes": [
            "Leaning forward too much",
            "Not actually touching heels to glutes",
        ],
        "video_url": "https://www.youtube.com/watch?v=Myo2qRPo5iA",
        "thumbnail_url": None,
        "calories_per_minute": 8.0,
    },
    {
        "name": "Skater Jump",
        "description": "Lateral plyometric exercise for agility and cardio.",
        "target_muscle": "cardio",
        "secondary_muscles": ["glutes", "quadriceps"],
        "difficulty": "intermediate",
        "equipment": "none",
        "category": "cardio",
        "default_sets": 3,
        "default_reps": 12,
        "default_duration_sec": None,
        "rest_time_sec": 45,
        "instructions": [
            "Stand on one leg",
            "Jump laterally to the other side, landing on the opposite foot",
            "Swing your arms for balance and momentum",
            "Repeat side to side",
        ],
        "common_mistakes": [
            "Not landing softly",
            "Jumping forward instead of laterally",
        ],
        "video_url": "https://www.youtube.com/watch?v=GPIM8VeQSdU",
        "thumbnail_url": None,
        "calories_per_minute": 10.0,
    },
    {
        "name": "Box Step-Up",
        "description": "Functional cardio and leg exercise using an elevated surface.",
        "target_muscle": "cardio",
        "secondary_muscles": ["quadriceps", "glutes"],
        "difficulty": "beginner",
        "equipment": "none",
        "category": "cardio",
        "default_sets": 3,
        "default_reps": 10,
        "default_duration_sec": None,
        "rest_time_sec": 45,
        "instructions": [
            "Stand in front of a sturdy bench or step",
            "Step up with one foot, driving through the heel",
            "Bring the other foot up to stand on top",
            "Step back down and alternate leading legs",
        ],
        "common_mistakes": [
            "Pushing off the back foot instead of driving with the front leg",
            "Using a surface that's too high",
        ],
        "video_url": "https://www.youtube.com/watch?v=dQqApCGd5Ss",
        "thumbnail_url": None,
        "calories_per_minute": 7.0,
    },

    # === FLEXIBILITY ===
    {
        "name": "Cat-Cow Stretch",
        "description": "Gentle spinal mobility exercise for warm-up or cool-down.",
        "target_muscle": "back",
        "secondary_muscles": ["core"],
        "difficulty": "beginner",
        "equipment": "none",
        "category": "flexibility",
        "default_sets": 3,
        "default_reps": 10,
        "default_duration_sec": None,
        "rest_time_sec": 30,
        "instructions": [
            "Start on all fours with hands under shoulders and knees under hips",
            "Inhale: arch your back and look up (cow)",
            "Exhale: round your spine and tuck your chin (cat)",
            "Flow between the two positions",
        ],
        "common_mistakes": [
            "Moving too quickly",
            "Not breathing with the movement",
        ],
        "video_url": "https://www.youtube.com/watch?v=kqnua4rHVVA",
        "thumbnail_url": None,
        "calories_per_minute": 2.0,
    },
    {
        "name": "Child's Pose",
        "description": "Restorative stretch for the back, hips, and shoulders.",
        "target_muscle": "back",
        "secondary_muscles": ["shoulders"],
        "difficulty": "beginner",
        "equipment": "none",
        "category": "flexibility",
        "default_sets": 1,
        "default_reps": None,
        "default_duration_sec": 60,
        "rest_time_sec": 0,
        "instructions": [
            "Kneel on the floor with toes together and knees apart",
            "Sit back on your heels and stretch your arms forward on the floor",
            "Rest your forehead on the ground and breathe deeply",
        ],
        "common_mistakes": [
            "Not relaxing fully into the stretch",
            "Holding breath",
        ],
        "video_url": "https://www.youtube.com/watch?v=2MJGg-dUKh0",
        "thumbnail_url": None,
        "calories_per_minute": 2.0,
    },

    # === RESISTANCE BAND EXERCISES ===
    {
        "name": "Band Pull-Apart",
        "description": "Upper back and rear delt exercise using a resistance band.",
        "target_muscle": "back",
        "secondary_muscles": ["shoulders"],
        "difficulty": "beginner",
        "equipment": "resistance_bands",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 15,
        "default_duration_sec": None,
        "rest_time_sec": 45,
        "instructions": [
            "Hold a band in front of you at shoulder height with arms extended",
            "Pull the band apart by squeezing your shoulder blades together",
            "Return to start with control",
        ],
        "common_mistakes": [
            "Using too much arm movement instead of back engagement",
            "Shrugging shoulders",
        ],
        "video_url": "https://www.youtube.com/watch?v=lSt7vRFcHzM",
        "thumbnail_url": None,
        "calories_per_minute": 3.0,
    },
    {
        "name": "Band Squat",
        "description": "Squat variation with added resistance from a band.",
        "target_muscle": "quadriceps",
        "secondary_muscles": ["glutes"],
        "difficulty": "intermediate",
        "equipment": "resistance_bands",
        "category": "strength",
        "default_sets": 3,
        "default_reps": 12,
        "default_duration_sec": None,
        "rest_time_sec": 60,
        "instructions": [
            "Stand on the band with feet shoulder-width apart",
            "Hold the band at shoulder level",
            "Squat down then stand back up against the band resistance",
        ],
        "common_mistakes": [
            "Band placement too loose",
            "Not maintaining tension throughout",
        ],
        "video_url": "https://www.youtube.com/watch?v=qCTXlTvzQNA",
        "thumbnail_url": None,
        "calories_per_minute": 6.0,
    },
]


async def seed_exercises():
    """Seed the exercise database if it's empty."""
    db = get_database()
    repo = ExerciseRepository(db)

    count = await repo.count()
    if count == 0:
        print(f"[Seed] Seeding {len(EXERCISES)} exercises...")
        await repo.insert_many(EXERCISES)
        print(f"[Seed] Seeded {len(EXERCISES)} exercises successfully!")
    else:
        print(f"[Seed] Exercise database already has {count} exercises, skipping seed.")
